In [55]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [56]:
# File path to the text file
local_filename = "/kaggle/input/babynamesbystate-zip/CA.TXT"
field_names = ['State', 'Gender', 'Year', 'Name', 'Count']

# Read the CSV file directly
babynamesCA = pd.read_csv(local_filename, header=None, names=field_names)

# Display the first few rows
babynamesCA.head()

  State Gender  Year      Name  Count
0    CA      F  1910      Mary    295
1    CA      F  1910     Helen    239
2    CA      F  1910   Dorothy    220
3    CA      F  1910  Margaret    163
4    CA      F  1910   Frances    134

**Question 1: Retrieve all records for the state 'CA' (California) from the `babynames` dataframe.**

In [57]:
babynamesCA

       State Gender  Year      Name  Count
0         CA      F  1910      Mary    295
1         CA      F  1910     Helen    239
2         CA      F  1910   Dorothy    220
3         CA      F  1910  Margaret    163
4         CA      F  1910   Frances    134
...      ...    ...   ...       ...    ...
413889    CA      M  2023      Ziah      5
413890    CA      M  2023    Ziaire      5
413891    CA      M  2023    Zidane      5
413892    CA      M  2023      Zyan      5
413893    CA      M  2023      Zyir      5

[413894 rows x 5 columns]

**Modified Question 1: Retrieve all records for the state 'CA' from the babynames dataframe, but exclude the years 1990 and 2000.**

In [58]:
babynamesCA.loc[~babynamesCA['Year'].isin([1990, 2000])]

       State Gender  Year      Name  Count
0         CA      F  1910      Mary    295
1         CA      F  1910     Helen    239
2         CA      F  1910   Dorothy    220
3         CA      F  1910  Margaret    163
4         CA      F  1910   Frances    134
...      ...    ...   ...       ...    ...
413889    CA      M  2023      Ziah      5
413890    CA      M  2023    Ziaire      5
413891    CA      M  2023    Zidane      5
413892    CA      M  2023      Zyan      5
413893    CA      M  2023      Zyir      5

[401346 rows x 5 columns]

**Question 2: Find all baby names in California for the year 2000.**

In [59]:
babynamesCA.loc[(babynamesCA['State'] == 'CA') & (babynamesCA['Year'] == 2000)]

       State Gender  Year      Name  Count
149062    CA      F  2000     Emily   2959
149063    CA      F  2000    Ashley   2831
149064    CA      F  2000  Samantha   2578
149065    CA      F  2000   Jessica   2485
149066    CA      F  2000  Jennifer   2265
...      ...    ...   ...       ...    ...
348605    CA      M  2000     Zarek      5
348606    CA      M  2000       Zen      5
348607    CA      M  2000     Zenon      5
348608    CA      M  2000    Zuriel      5
348609    CA      M  2000      Zyon      5

[6285 rows x 5 columns]

**Modified Question 2: Find all baby names in California for the year 2000 and sort them in descending order based on the number of occurrences.**

In [60]:
df = babynamesCA.loc[(babynamesCA['Year'] == 2000)]
df.sort_values(by=['Count'], ascending=False)

       State Gender  Year        Name  Count
346093    CA      M  2000      Daniel   4342
346094    CA      M  2000     Anthony   3840
346095    CA      M  2000        Jose   3804
346096    CA      M  2000      Andrew   3600
346097    CA      M  2000     Michael   3572
...      ...    ...   ...         ...    ...
152465    CA      F  2000  Francessca      5
152464    CA      F  2000   Florencia      5
152463    CA      F  2000    Fiorella      5
152462    CA      F  2000   Felicitas      5
348609    CA      M  2000        Zyon      5

[6285 rows x 5 columns]

**Question 3: Get all female baby names for the state of New York ('NY') from the year 1995.**

In [61]:
local_filename = "/kaggle/input/babynamesbystate-zip/NY.TXT"
babynamesNY = pd.read_csv(local_filename, header=None, names=field_names)

babynamesNY.loc[(babynamesNY['Gender'] == 'F') & (babynamesNY['Year'] == 1995)]

       State Gender  Year      Name  Count
109699    NY      F  1995    Ashley   2056
109700    NY      F  1995  Samantha   1892
109701    NY      F  1995   Jessica   1853
109702    NY      F  1995     Emily   1687
109703    NY      F  1995    Amanda   1578
...      ...    ...   ...       ...    ...
112015    NY      F  1995    Zaynah      5
112016    NY      F  1995    Zeinab      5
112017    NY      F  1995      Zena      5
112018    NY      F  1995     Zenab      5
112019    NY      F  1995   Zuleyma      5

[2321 rows x 5 columns]

**Modified Question 3: Get the top 10 female baby names in New York ('NY') from the year 1995 with the highest counts.**

In [62]:
babynamesNY.loc[(babynamesNY['Gender'] == 'F') & (babynamesNY['Year'] == 1995)].sort_values(by='Count', ascending=False).head(10)

       State Gender  Year       Name  Count
109699    NY      F  1995     Ashley   2056
109700    NY      F  1995   Samantha   1892
109701    NY      F  1995    Jessica   1853
109702    NY      F  1995      Emily   1687
109703    NY      F  1995     Amanda   1578
109704    NY      F  1995     Nicole   1484
109705    NY      F  1995      Sarah   1415
109706    NY      F  1995  Stephanie   1235
109707    NY      F  1995   Jennifer   1138
109708    NY      F  1995     Rachel   1103

# ****You can solve following question for any State (if state is not mentioned)****

**Question 4: Select the first 10 rows from the `babynames` dataframe.**

In [63]:
babynamesCA.head(10)

  State Gender  Year       Name  Count
0    CA      F  1910       Mary    295
1    CA      F  1910      Helen    239
2    CA      F  1910    Dorothy    220
3    CA      F  1910   Margaret    163
4    CA      F  1910    Frances    134
5    CA      F  1910       Ruth    128
6    CA      F  1910     Evelyn    126
7    CA      F  1910      Alice    118
8    CA      F  1910   Virginia    101
9    CA      F  1910  Elizabeth     93

**Modified Question 4: Select the first 20 rows and only include those rows where the baby count is even.**

In [64]:
babynamesCA.loc[(babynamesCA["Count"] % 2 == 0)].head(20)

   State Gender  Year       Name  Count
2     CA      F  1910    Dorothy    220
4     CA      F  1910    Frances    134
5     CA      F  1910       Ruth    128
6     CA      F  1910     Evelyn    126
7     CA      F  1910      Alice    118
11    CA      F  1910      Marie     90
12    CA      F  1910    Mildred     90
13    CA      F  1910       Rose     74
14    CA      F  1910      Hazel     68
16    CA      F  1910  Josephine     66
17    CA      F  1910    Lucille     66
20    CA      F  1910       Edna     62
21    CA      F  1910    Eleanor     60
22    CA      F  1910   Marjorie     60
25    CA      F  1910      Edith     58
26    CA      F  1910      Doris     56
27    CA      F  1910      Irene     56
30    CA      F  1910      Ethel     52
33    CA      F  1910     Esther     44
36    CA      F  1910      Betty     40

**Question 5: Retrieve the 50th to 60th rows and only display the 'State', 'Name', and 'Count' columns.**

In [65]:
babynamesCA.iloc[50:61, [0,3,4]]

   State       Name  Count
50    CA     Myrtle     30
51    CA    Pauline     30
52    CA       Ruby     30
53    CA       Emma     29
54    CA        Eva     29
55    CA  Genevieve     29
56    CA      Sarah     29
57    CA      Anita     28
58    CA        Ida     28
59    CA      Julia     28
60    CA     Martha     28

**Modified Question 5: Retrieve rows from 50 to 100, but only display the rows where the count is greater than 500 and include only the 'State', 'Name', and 'Count' columns.**

In [66]:
bigCount = babynamesCA.loc[babynamesCA['Count'] > 500]
bigCount.iloc[50:101, [0,3,4]]

     State      Name  Count
5713    CA      Mary   1829
5714    CA     Betty   1169
5715    CA   Dorothy   1167
5716    CA   Barbara    874
5717    CA  Margaret    806
5718    CA     Helen    736
5719    CA  Virginia    717
5720    CA      Ruth    577
5721    CA   Frances    529
6368    CA      Mary   1958
6369    CA     Betty   1464
6370    CA   Dorothy   1173
6371    CA   Barbara   1014
6372    CA     Helen    820
6373    CA  Margaret    818
6374    CA  Virginia    785
6375    CA  Patricia    655
6376    CA      Ruth    617
7058    CA      Mary   1890
7059    CA     Betty   1529
7060    CA   Barbara   1073
7061    CA   Dorothy   1053
7062    CA     Helen    757
7063    CA  Virginia    754
7064    CA  Margaret    727
7065    CA  Patricia    727
7066    CA      Ruth    589
7067    CA    Gloria    545
7068    CA   Frances    506
7760    CA      Mary   1721
7761    CA     Betty   1359
7762    CA   Barbara   1306
7763    CA   Dorothy    975
7764    CA  Margaret    725
7765    CA     Helen    718
7766    CA  Patricia    718
7767    CA  Virginia    625
7768    CA      Ruth    585
8446    CA      Mary   1816
8447    CA   Barbara   1410
8448    CA     Betty   1333
8449    CA   Dorothy    919
8450    CA  Patricia    802
8451    CA     Helen    683
8452    CA  Margaret    613
8453    CA   Shirley    589
8454    CA  Virginia    576
8455    CA    Gloria    513
9126    CA      Mary   1785
9127    CA   Barbara   1463
9128    CA     Betty   1222

**Question 6: Get the row at index 100 and display it.**

In [67]:
babynamesCA.iloc[100]

State       CA
Gender       F
Year      1910
Name      Irma
Count       16
Name: 100, dtype: object

**Modified Question 6: Retrieve the row at index 100, then calculate the sum of all the numeric columns in the dataset for this row.**

In [68]:
row = babynamesCA.iloc[100:101]
sum = row.select_dtypes(include='number').sum().sum()
print(sum)

1926

**Question 7: Retrieve the 'Name' and 'Count' columns for the first 5 rows.**

In [69]:
babynamesCA.iloc[:5, [3,4]]

       Name  Count
0      Mary    295
1     Helen    239
2   Dorothy    220
3  Margaret    163
4   Frances    134

**Modified Question 7: Retrieve the 'Name' and 'Count' columns for the first 10 rows, but only include rows where the name starts with a vowel.**

In [70]:
rowsTen = babynamesCA.iloc[:10]
vowelRows = rowsTen[rowsTen['Name'].str.startswith(tuple('AEIOUaeiou'))]
result = vowelRows[['Name', 'Count']]

print(result)

        Name  Count
6     Evelyn    126
7      Alice    118
9  Elizabeth     93

**Question 8: Find all names in the dataset with a count greater than 1000.**

In [71]:
import glob

folder_path = "/kaggle/input/babynamesbystate-zip/"
all_files = glob.glob(f"{folder_path}/*.TXT")
field_names = ['State', 'Gender', 'Year', 'Name', 'Count']
babynames = pd.concat((pd.read_csv(file, header=None, names=field_names) for file in all_files), ignore_index=True)
print(babynames)

        State Gender  Year       Name  Count
0          VA      F  1910       Mary    848
1          VA      F  1910   Virginia    270
2          VA      F  1910  Elizabeth    254
3          VA      F  1910       Ruth    218
4          VA      F  1910   Margaret    209
...       ...    ...   ...        ...    ...
6504156    CA      M  2023       Ziah      5
6504157    CA      M  2023     Ziaire      5
6504158    CA      M  2023     Zidane      5
6504159    CA      M  2023       Zyan      5
6504160    CA      M  2023       Zyir      5

[6504161 rows x 5 columns]

**Modified Question 8: Find all names in the dataset with a count greater than 5000, but exclude the state 'TX'.**

In [72]:
babynames[(babynames['Count'] > 5000) & (babynames['State'] != 'TX')]

        State Gender  Year     Name  Count
1401942    NY      F  1915     Mary   5342
1402661    NY      F  1916     Mary   5497
1403393    NY      F  1917     Mary   5502
1404117    NY      F  1918     Mary   5523
1404886    NY      F  1919     Mary   5060
...       ...    ...   ...      ...    ...
6418906    CA      M  1993   Daniel   5229
6418907    CA      M  1993     Jose   5023
6421459    CA      M  1994   Daniel   5116
6421460    CA      M  1994  Michael   5098
6424053    CA      M  1995   Daniel   5007

[685 rows x 5 columns]

**Question 9: Get all baby names that start with the letter 'A' from the state of Texas (TX).**

In [73]:
babynames.loc[(babynames['Name']).str.startswith(tuple("Aa")) & (babynames['State'] == 'TX')]

        State Gender  Year     Name  Count
5463382    TX      F  1910    Annie    277
5463402    TX      F  1910    Alice    149
5463420    TX      F  1910     Anna    117
5463421    TX      F  1910     Alma    116
5463456    TX      F  1910      Ada     63
...       ...    ...   ...      ...    ...
5845733    TX      M  2023   Ayrton      5
5845734    TX      M  2023    Ayson      5
5845735    TX      M  2023   Azaias      5
5845736    TX      M  2023  Azariel      5
5845737    TX      M  2023    Azeem      5

[40502 rows x 5 columns]

**Question 10: Get the first 5 rows for the state 'CA', then select only the 'Year', 'Name', and 'Count' columns.**

In [74]:
babynamesCA.iloc[:5,[2,3,4]]

   Year      Name  Count
0  1910      Mary    295
1  1910     Helen    239
2  1910   Dorothy    220
3  1910  Margaret    163
4  1910   Frances    134